### ISSUE TITLE
程序闪退

### ISSUE THREAD

**Issue by interuptted** [deadw1nter/YoutubeToBilibili#1]
按照readme配置好了，但是执行任何一个.py文件都闪退（？

**Comment by deadw1nter** [comment]
数据库里的``channel`` 表里有频道吗?

**Comment by interuptted** [comment]
没...我用的是境外的服务器，是可以访问到的

**Comment by interuptted** [comment]
什么错误也没有出现，就结束了x

**Comment by deadw1nter** [comment]
脚本需要mysql数据库运行，要确保 ``channel`` 表里面有频道链接。[因为需要读表里面的信息才能获取频道的信息](https://github.com/deadw1nter/YoutubeToBilibili/blob/master/youtube.py#L84-L86)

**Comment by deadw1nter** [comment]
可以在mysql里使用 ``INSERT INTO channel (name, url)
VALUES ('频道名字', '频道链接');`` 来插入信息。其中频道链接需要 ``/channel/频道id`` 中的频道id， 如链接 ``channel/UCM2ipUbm_Bg-bkLMwwchd3Q`` 那么频道链接则为 ''UCM2ipUbm_Bg-bkLMwwchd3Q''

**Comment by interuptted** [comment]
=== RESTART: C:\Users\Administrator\Desktop\YoutubeToBilibili-master\main.py ===
[Main] Checking UCc6V5dmpJtwb2UNmY0ssxTQ
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\YoutubeToBilibili-master\main.py", line 7, in <module>
    monitor.check_videos()
  File "C:\Users\Administrator\Desktop\YoutubeToBilibili-master\youtube.py", line 88, in check_videos
    videos = json.loads(body.text)['items']
KeyError: 'items'

**Comment by interuptted** [comment]
可以使用了，真是麻烦您了，感谢！

**Comment by interuptted** [comment]
下载完就停了（？
没有下一步的动作

**Comment by interuptted** [comment]
downloading video. id: WxcSYut1DM8 status:4
[Download] Start downloading
Removing cache dir C:\Users\Administrator/.cache\youtube-dl .
.
[youtube] WxcSYut1DM8: Downloading webpage
[youtube] WxcSYut1DM8: Downloading MPD manifest
[download] videos\WxcSYut1DM8.mp4 has already been downloaded and merged
(2, 'No such file or directory')
>>>

**Comment by deadw1nter** [comment]
根目录下有videos这个文件夹吗?如果没有的话可能会上传失败.封面一样

**Comment by interuptted** [comment]
有的

**Comment by deadw1nter** [comment]
hmm 试一下新的commit?

**Comment by interuptted** [comment]
可以了 都正常了w
感谢
