### ISSUE TITLE
超长稿件标题过长上传失败

### ISSUE THREAD

**Issue by interuptted** [deadw1nter/YoutubeToBilibili#2]
标题超过80字符导致上传任务失败，能否添加标题字数限制，自动删减超出字符

**Comment by interuptted** [comment]
[youtube] 8dpdNWd2bBs: Downloading webpage
[youtube] 8dpdNWd2bBs: Downloading js player 7bc032d0
[youtube] 8dpdNWd2bBs: Downloading js player 7bc032d0
[youtube] 8dpdNWd2bBs: Downloading MPD manifest
[download] videos\8dpdNWd2bBs.mp4 has already been downloaded and merged
[Download] All done
[Upload] Start uploading
[Upload] Uploaded video file successfully.
[Upload] Uploaded thubmnail successfully.
[Upload] Submitting
(21103, '稿件标题过长,已经超过80个字符')

**Comment by deadw1nter** [comment]
已修复
