### ISSUE TITLE
视频消失,上传失败

### ISSUE THREAD

**Issue by interuptted** [deadw1nter/YoutubeToBilibili#3]
[download] 100% of 2.72MiB in 00:00
[ffmpeg] Merging formats into "./videos/eKiJqKLh2-E.mp4"
Deleting original file ./videos/eKiJqKLh2-E.f299.mp4 (pass -k to keep)
Deleting original file ./videos/eKiJqKLh2-E.f140.m4a (pass -k to keep)
[Download] All done
[Upload] Start uploading
[Upload] Failed to upload video file. Make sure the video file exists

上传好久后突然提示文件不存在
有概率出现此错误

**Comment by deadw1nter** [comment]
这个大概率是因为境外服务器连国内的服务器速度慢，导致上传视频文件失败。目前我没有解决办法

**Comment by interuptted** [comment]
了解
